### PR TITLE
feat: get openzaak cases with apollo client through gql

### PR DESCRIPTION
**Pull request by mritense**
Readme and various docker configuration files expanded to support new @nl-portal/api library and to explain configuration and use of GraphQL in the application. Currently, to test the new back-end connection, [this branch](https://github.com/valtimo-platform/valtimo-portal-engine/pull/71) of portal-engine must be running. 
Closes https://ritense.tpondemand.com/entity/30581-apollo-client-inbouwen-in-nl-portal.

### CODE REVIEW

**Comment by bddjong** [comment]
Can't review properly due to invalid token issues with the graphql request. Curious if it works for @mjcarsjens

**Comment by bddjong** [comment]
> Can't review properly due to invalid token issues with the graphql request. Curious if it works for @mjcarsjens

Token issues was due to a misconfiguration between the portal and API. In order to avoid the token issues, make sure you've configured the valtimo portal engine to use the same keycloak realm as the portal. In order to do this, change the following config in the valtimo portal engine: 
File: `app/src/main/resources/config/application.yml`
Property: `issuer-uri: https://keycloak.valtimo.nl/auth/realms/gemeente-denhaag-public-non-production`

**Review by Test-Automation-Engineer — APPROVED** [review]
I've reviewed the files regarding docker etc. Looking good!
@bddjong @mjcarsjens Please review, I would really like this to have in the master branch.

**Review by bddjong — APPROVED** [review]
Looks good! Small question, would it be useful to have tests for the third party integration / queries?

**Pull request merged**
